# CONSTRAINTS da table Pagina
ALTER TABLE CRUD_RTFs.Pagina
ADD CONSTRAINT FOREIGN KEY (id_rtf) REFERENCES CRUD_RTFs.RTFs(id);

ALTER TABLE CRUD_RTFs.Pagina
ADD COLUMN id_rtf int;



# CONSTRAINTS da table Cenarios
ALTER TABLE CRUD_RTFs.Cenarios
ADD COLUMN id_rtf int;

ALTER TABLE CRUD_RTFs.Cenarios
ADD COLUMN id_pagina int;

ALTER TABLE CRUD_RTFs.Cenarios
ADD CONSTRAINT FOREIGN KEY (id_rtf) REFERENCES CRUD_RTFs.RTFs(id);

ALTER TABLE CRUD_RTFs.Cenarios
ADD CONSTRAINT FOREIGN KEY (id_pagina) REFERENCES CRUD_RTFs.Pagina(id_pagina);

